---

isDebug: true
listen:
  type: sock
  bind_ip: 0.0.0.0
  port: 10000
storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
mongodb:
  host: localhost
  port: 27017
  database: user_service
  username:
  password:
  auth_db:
  collection: users