POST http://localhost:1234/users
Content-Type: application/json

{}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

PUT http://localhost:1234/users/125
Content-Type: application/json

{}

###

PATCH http://localhost:1234/users/125
Content-Type: application/json

{}

###

DELETE http://localhost:1234/users/125
Content-Type: application/json

{}

###
